apiVersion: v1
kind: Pod
metadata:
  name: mysecret-vol-pod
spec:
  containers:
  - name: mysecret-vol-container
    image: redis
    env:
    - name: SECRET_USER
      valueFrom:
        secretKeyRef:
        - name: mysecret
          key: username.txt
    - name: SECRET_PWD
      valueFrom:
        secretKeyRef:
        - name: mysecret
          key: passward.txt

