apiVersion: v1
kind: Pod
metadata:
  name: mysecret-vol-pod
spec:
  containers:
  - name: mysecret-vol-container
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/sensitive"
  volumes:
  - name: foo
    secret:
      secretName: mysecret
