apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers:
  - name: redis-container
    image: redis
    env:
      - name: FILE_1
        valueFrom:
          configMapKeyRef:
            name: redis-config-map
            key: file.1
      - name: FILE_2
        valueFrom:
          configMapKeyRef:
            name: redis-config-map
            key: file.2
  restartPolicy: Never

